---
# abz_app


- name: "[ {{ service_name }} ]: Deploying service"
  tags: "{{ service_name }}"
  block:
    - name: "[ {{ service_name }} ]: Configuring config"
      include_tasks: "../config.yaml"
      loop:
        - nginx.conf
      loop_control:
        loop_var: config_item

    - name: "[ {{ service_name }} ]: Run service Deploy"
      community.docker.docker_swarm_service:
        name: "{{ service_name }}"
        image: "{{ REGISTRY_NAME }}{{ service_name }}:{{ service_version }}"
        state: present
        networks:
          - name: "{{ NETWORK_NAME }}"
        publish:
          - mode: ingress
            protocol: tcp
            published_port: 8080
            target_port: 8080
        configs:
          - config_name: "{{ service_name }}-nginx.conf"
            filename: "/etc/nginx/nginx.conf"
