FROM node:20 AS build-stage

WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install

FROM node:20

WORKDIR /usr/src/app
COPY --from=build-stage /usr/src/app/node_modules /usr/src/app/node_modules
COPY . .
RUN npm run generate
