version: '3'

services:
  registry:
    image: registry:2
    container_name: registry
    restart: always
    volumes:
      - data:/var/lib/registry
    ports:
      - "5000:5000"

volumes:
  data:
