export enum API_APP_ENV {
    LOCAL = 'local',
    DEVELOPMENT = 'development',
    STAGING = 'staging',
    PRODUCTION = 'production',
    TESTING = 'testing',
    LOAD_TESTING = 'load_testing',
}

export const API_APP_ENV_MAP = {
    local: API_APP_ENV.LOCAL,
    development: API_APP_ENV.DEVELOPMENT,
    staging: API_APP_ENV.STAGING,
    production: API_APP_ENV.PRODUCTION,
    testing: API_APP_ENV.TESTING,
    load_testing: API_APP_ENV.LOAD_TESTING
}

export enum ENV_VARS {
    DATABASE_URL = 'DATABASE_URL',
    API_APP_ENV = 'API_APP_ENV',
    API_LOG_LEVEL = 'API_LOG_LEVEL',
    API_PROTOCOL = 'API_PROTOCOL',
    API_HOST = 'API_HOST',
    API_PORT = 'API_PORT',
    API_JWT_ACCESS_SECRET = 'API_JWT_ACCESS_SECRET',
    API_JWT_ACCESS_EXPIRES_IN = 'API_JWT_ACCESS_EXPIRES_IN',
    API_JWT_ALGORITHM = 'API_JWT_ALGORITHM',
    API_JWT_CACHE_PREFIX = 'API_JWT_CACHE_PREFIX',
    API_JWT_CACHE_TTL = 'API_JWT_CACHE_TTL',
    API_CONVERTER_URL = 'API_CONVERTER_URL',
    API_PAGE_COUNT_ROWS = 'API_PAGE_COUNT_ROWS',
    API_REDIS_DB ='API_REDIS_DB',
    API_REDIS_PORT ='API_REDIS_PORT',
    API_REDIS_HOST ='API_REDIS_HOST',
    API_REDIS_CACHE_TTL = 'API_REDIS_CACHE_TTL',
    API_UPLOAD_FOLDER_PATH = 'API_UPLOAD_FOLDER_PATH',
    API_IMAGES_URL_PATH = 'API_IMAGES_URL_PATH',
    API_MAX_PHOTO_SIZE = 'API_MAX_PHOTO_SIZE',
    API_DEFAULT_PHOTO_FORMAT = 'API_DEFAULT_PHOTO_FORMAT'
}
