---
- name: Check if Docker is installed
  command: docker --version
  register: docker_installed
  ignore_errors: true

- name: Download Docker convenience script
  get_url:
    url: https://get.docker.com
    dest: /tmp/get-docker.sh
    mode: '0755'
  when: docker_installed.rc != 0

- name: Install Docker using the convenience script
  become: true
  command: sh /tmp/get-docker.sh
  when: docker_installed.rc != 0

- name: Create Docker group
  become: true
  group:
    name: docker
    state: present

- name: Add user to Docker group
  become: true
  user:
    name: "{{ user }}"
    groups: docker
    append: true

- name: Reboot
  become: true
  reboot:
    reboot_timeout: 3600

- name: "Run hello-world container"
  command: docker run hello-world
  register: hello_world_output
  failed_when: "'Hello from Docker!' not in hello_world_output.stdout"
