---
- name: "[ {{ service_name }} ]: Deploying service"
  tags: "{{ service_name }}"
  block:
    - name: "[ {{ service_name }} ]: Run service Deploy"
      community.docker.docker_swarm_service:
        name: "{{ service_name }}"
        image: "{{ image_name }}:{{ service_version }}"
        state: "present"
        networks:
          - name: "{{ NETWORK_NAME }}"
        publish:
          - mode: ingress
            protocol: tcp
            published_port: "{{ POSTGRES_ENV_VARS.PORT }}"
            target_port: 5432
        healthcheck:
          test: ["CMD-SHELL", "sh -c 'pg_isready -U {{ POSTGRES_ENV_VARS.USER }} -d {{ POSTGRES_ENV_VARS.DB }}'"]
          interval: 10s
          timeout: 5s
          retries: 5
        env:
          POSTGRES_USER: "{{ POSTGRES_ENV_VARS.USER }}"
          POSTGRES_PASSWORD: "{{ POSTGRES_ENV_VARS.PASSWORD }}"
          POSTGRES_DB: "{{ POSTGRES_ENV_VARS.DB }}"
        mounts:
          - source: "abz_postgres_prod"
            target: "/var/lib/postgresql"
            type: volume
